name: Deploy to Hosting

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -p 2222 69.6.201.152 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -p 2222 joseal61@69.6.201.152 << 'EOF'
            cd ~/public_html

            if [ ! -d ".git" ]; then
              git clone https://github.com/otakusnowden/taquerosweb.git .
            else
              git pull origin master
            fi
          EOF
